name: 'Conditional Composite'
description: 'Test composite run step conditionals'
inputs:
  exit-code:
    description: 'Action fails if set to non-zero'
    default: '0'
  child-exit-code:
    description: 'Nested Action fails if set to non-zero'
    default: '0'

outputs:
  status-error:
    description: "Statuses should not match if exit-codes are different"

runs:
    using: "composite"
    steps:
      - uses: ./action-status
        id: action-status
        with:
          exit-code: ${{ inputs.child-exit-code }}

      - run: exit ${{ inputs.exit-code }}
        shell: bash

      - run: if [ ${{ github.action_status == steps.action-status.status-after }} ] then echo "::set-output name=status-error::1"
        shell: bash
        if: ${{ inputs.exit-code != inputs.child-exit-code }}

      - run: if [ ${{ github.action_status != steps.action-status.status-after }} ] then echo "::set-output name=status-error::1"
        shell: bash
        if: ${{ inputs.exit-code == inputs.child-exit-code }}