name: 'Nested Conditional Composite'
description: 'Test composite run step conditionals'
inputs:
  exit-code:
    description: 'Action fails if set to non-zero'
    default: '0'
  child-exit-code:
    description: 'Child Action fails if set to non-zero'
    default: '0'
  
outputs:
  default:
    description: "Did step run with default?"
    value: ${{ steps.default-conditional.outputs.default }}
  success:
    description: "Did step run with success?"
    value: ${{ steps.success-conditional.outputs.success }}
  failure:
    description: "Did step run with failure?"
    value: ${{ steps.failure-conditional.outputs.failure }}
  always:
    description: "Did step run with always?"
    value: ${{ steps.always-conditional.outputs.always }}

runs:
    using: "composite"
    steps:
      - run: exit ${{ inputs.exit-code }}
        shell: bash

      - uses: ./conditional-composite
        id: composite-action
        with:
          exit-code: ${{ inputs.child-exit-code }}
        if: always()

      - run: if [ -z "${{ steps.composite-action.outputs.default }}" ]; then exit 1; else echo "Success"; fi
        name: step-default
        shell: bash
        if: inputs.child-exit-code != 1
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then exit 1; else echo "Success"; fi
        name: step-success
        shell: bash
        if: inputs.child-exit-code != 1
      - run: if [[ ! -z "${{ steps.composite-action.outputs.failure }}" ]]; then exit 1; else echo "Success"; fi
        name: step-failure
        shell: bash
        if: inputs.child-exit-code != 1
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then exit 1; else echo "Success"; fi
        name: step-always
        shell: bash
        if: inputs.child-exit-code != 1

      - run: if [[ ! -z "${{ steps.composite-action.outputs.default }}" ]]; then exit 1; else echo "Success"; fi
        name: step-default
        shell: bash
        if: inputs.child-exit-code == 1
      - run: if [[ ! -z "${{ steps.composite-action.outputs.success }}" ]]; then exit 1; else echo "Success"; fi
        name: step-success
        shell: bash
        if: inputs.child-exit-code == 1
      - run: if [ -z "${{ steps.composite-action.outputs.failure }}" ]; then exit 1; else echo "Success"; fi
        name: step-failure
        shell: bash
        if: inputs.child-exit-code == 1
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then exit 1; else echo "Success"; fi
        name: step-always
        shell: bash
        if: inputs.child-exit-code == 1