name: 'Conditional Composite'
description: 'Test composite run step conditionals'
inputs:
  exit-code:
    description: 'Action fails if set to non-zero'
    default: '0'
  child-exit-code:
    description: 'Nested Action fails if set to non-zero'
    default: '0'
outputs:\
  status-error:
    description: "Statuses should not match if exit-codes are different"
    value: ${{ steps.status-error.outputs.status-error }}

runs:
    using: "composite"
    steps:
      - run: exit ${{ inputs.exit-code }}
        shell: bash

      - uses: /action-status
        id: action-status
        with:
          exit-code: ${{ inputs.child-exit-code }}

      # asserts that actions_status works independently between actions
      - run: if [ ${{ (inputs.exit-code != inputs.child-exit-code && github.action_status == steps.action-status.status-after) || (inputs.exit-code == inputs.child-exit-code && github.action_status != steps.action-status.status-after) }} ] then echo "::set-output name=status-error::1"
        id: status-error
        shell: bash
