name: 'Nested node pre-post'
description: 'Provide a description here'
author: 'Your name or organization here'

runs:
    using: "composite"
    steps:
      - uses: fhammerl/canary/node-pre-post-success@main