name: Action Status is not Set on Job level

on:
  workflow_dispatch:
jobs:
  action-status-set-correctly:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: exit 1
        name: Action status is not be available from job level
        if: ${{ github.action_status }}

      - uses: ./action-status
        id: action-status

      - run: exit 1
        name: Action status is not be available from job level
        if: ${{ github.action_status }}

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()
