name: Action Status - Composite Action Job Step with if:failure

on:
  workflow_dispatch:
jobs:
  action-status-set-correctly:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - uses: ./action-status
        id: composite-action

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()
