name: Action Status in Composite Actions
on:
  workflow_dispatch:
jobs:
  action-status-set-correctly-action-success:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - uses: ./action-status
        id: action-status

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - run: exit 1
        name: Action status before should be 'Success'
        if: steps.action-status.outputs.status-before != 'Success'

      - run: exit 1
        name: Action status after should be 'Success'
        if: steps.action-status.outputs.status-after != 'Success'

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()

  action-status-set-correctly-action-fail:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - uses: ./action-status
        id: action-status

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - run: exit 1
        name: Action status before should be 'Failure'
        if: steps.action-status.outputs.status-before != 'Success'

      - run: exit 1
        name: Action status after should be 'Failure'
        if: steps.action-status.outputs.status-after != 'Failure'

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()

