
name: Action Statuses in Nested Conditionals are Independent from each other

on:
  workflow_dispatch:

jobs:
  nested-conditionals:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        exit-code: [0, 1]
        child-exit-code: [0, 1]
    steps:
      - uses: actions/checkout@v2
      - uses: ./nested-action-status
        id: nested-action-status
        continue-on-error: true
        with:
          exit-code: ${{matrix.exit-code}}
          child-exit-code: ${{matrix.child-exit-code}}

      - run: exit 1
        name: status-error
        if: ${{ steps.nested-action-status.outputs.status-error }}

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()