
name: Basic Conditional

on:
  workflow_dispatch:

jobs:
  happy-path:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./conditional-composite
        id: composite-action
      - run: if [ -z "${{ steps.composite-action.outputs.default }}" ]; then exit 1; else echo "Success"; fi
        name: step-default
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then exit 1; else echo "Success"; fi
        name: step-success
      - run: if [[ ! -z "${{ steps.composite-action.outputs.failure }}" ]]; then exit 1; else echo "Success"; fi
        name: step-failure
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then exit 1; else echo "Success"; fi
        name: step-always

  angry-path:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./conditional-composite
        id: composite-action
        with:
          exit-code: 1
        continue-on-error: true
      - run: if [[ ! -z "${{ steps.composite-action.outputs.default }}" ]]; then exit 1; else echo "Success"; fi
        name: step-default
      - run: if [[ ! -z "${{ steps.composite-action.outputs.success }}" ]]; then exit 1; else echo "Success"; fi
        name: step-success
      - run: if [ -z "${{ steps.composite-action.outputs.failure }}" ]; then exit 1; else echo "Success"; fi
        name: step-failure
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then exit 1; else echo "Success"; fi
        name: step-always
