
name: Conditionals in Nested Conditionals are Independent from each other

on:
  workflow_dispatch:

jobs:
  nested-conditionals:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        exit-code: [0, 1]
        child-exit-code: [0, 1]
    steps:
      - uses: actions/checkout@v2
      - uses: ./nested-conditional-composite
        id: composite-action
        continue-on-error: true
        with:
          exit-code: ${{matrix.exit-code}}
          child-exit-code: ${{matrix.child-exit-code}}
      - run: if [ -z "${{ steps.composite-action.outputs.failure }}" ]; then exit 1; else echo "Expected a failure and got one!"; fi
        if: matrix.exit-code == 1 || matrix.child-exit-code == 1
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then exit 1; else echo "Expected a success and got one!"; fi
        if: matrix.exit-code == 0 && matrix.child-exit-code == 0