name: Failing Job - Composite Action Job Step with if:failure

on:
  workflow_dispatch:
jobs:
  runs-default-success-always:
    continue-on-error: true
    name: Runs steps with no condition, success or always
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - uses: ./conditional-composite
        id: composite-action
        if: failure()
      - run: if [ -z "${{ steps.composite-action.outputs.default }}" ]; then echo "'default()' Success"; else echo '::set-output name=success::1'; fi
        id: step-default
        if: always()
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then echo "'success()' Success"; else echo '::set-output name=success::1'; fi
        id: step-success
        if: always()
      - run: if [[ ! -z "${{ steps.composite-action.outputs.failure }}" ]]; then echo "'failure()' Success"; else echo '::set-output name=success::1'; fi
        id: step-failure
        if: always()
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then echo "'always()' Success"; else echo '::set-output name=success::1'; fi
        id: step-always
        if: always()


  check-correct-composite-steps-ran:
    needs: runs-default-success-always
    name: Check correct composite steps ran
    runs-on: self-hosted
    steps:
      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: ${{ needs.runs-default-success-always.steps.step-default.outputs.success || needs.runs-default-success-always.steps.step-success.outputs.success || needs.runs-default-success-always.steps.step-failure.outputs.success || needs.runs-default-success-always.steps.step-always.outputs.success }} 

      - run: echo 'in case of actual failure do slack webhook'
        if: failure()
