name: Failing Composite Action with continue-on-error - Job still Succeeds 

on:
  workflow_dispatch:
jobs:
  runs-job-with-failing-action:
    name: Runs steps with no condition, success or always
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./conditional-composite
        id: composite-action
        with: 
          exit-code: 1
        continue-on-error: true

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()
