name: Failing Job - Composite Action Job Step with if:failure

on:
  workflow_dispatch:
jobs:
  runs-default-success-always:
    name: Runs steps with no condition, success or always
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - uses: ./conditional-composite
        id: composite-action
        if: failure()
      - run: if [ -z "${{ steps.composite-action.outputs.default }}" ]; then echo '::set-output name=failed::1'; else echo "'default()' Success"; fi
        id: step-default
        if: always()
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then echo '::set-output name=failed::1'; else echo "'success()' Success"; fi
        id: step-success
        if: always()
      - run: if [[ ! -z "${{ steps.composite-action.outputs.failure }}" ]]; then echo '::set-output name=failed::1'; else echo "'failure()' Success"; fi
        id: step-failure
        if: always()
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then echo '::set-output name=failed::1'; else echo "'always()' Success"; fi
        id: step-always
        if: always()

      - run: echo 'really fail' && exit 1
        id: todo-slack-webhook
        if: ${{ steps.step-default.outputs.failed || steps.step-success.outputs.failed || steps.step-failure.outputs.failed || steps.step-always.outputs.failed }} 
