name: Failing Job - Composite Action Job Step with if:failure

on:
  workflow_dispatch:
jobs:
  runs-default-success-always:
    outputs:
      default: ${{ steps.composite-action.outputs.default }}
      success: ${{ steps.composite-action.outputs.success }}
      failure: ${{ steps.composite-action.outputs.failure }}
      always: ${{ steps.composite-action.outputs.always }}
    continue-on-error: true
    name: Runs steps with no condition, success or always
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - uses: ./conditional-composite
        id: composite-action
        if: always()

  check-correct-composite-steps-ran:
    needs: runs-default-success-always
    name: Check correct composite steps ran
    runs-on: self-hosted
    steps:
      # - run: echo 'in case of actual failure do slack webhook' && exit 1
      #   id: todo-slack-webhook
      #   if: ${{ needs.runs-default-success-always.outputs.default || needs.runs-default-success-always.outputs.success || needs.runs-default-success-always.outputs.failure || needs.runs-default-success-always.outputs.always }} 

      # - run: echo 'in case of actual failure do slack webhook'
      #   if: failure()

      - run: echo '${{ needs.runs-default-success-always.outputs.default }}'
      - run: echo '${{ needs.runs-default-success-always.outputs.success }}'
      - run: echo '${{ needs.runs-default-success-always.outputs.failure }}'
      - run: echo '${{ needs.runs-default-success-always.outputs.always }}'