name: Nested Node Action - Pre-Post Conditional
on:
  workflow_dispatch:

jobs:
  nested-node-pre-post-on-success:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main
  nested-node-pre-post-on-success-job-failing:
    runs-on: self-hosted
    steps:
      - run: exit 1
      - uses: fhammerl/canary/nested-node-pre-post-on-failure@main
        if: failure()

  nested-node-pre-post-on-failure:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main
        with:
          exit-code: 1
  nested-node-pre-post-on-failure-job-failing:
    runs-on: self-hosted
    steps:
      - run: exit 1
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main
        with:
          exit-code: 1
        if: failure()
