name: Nested Node Action - Pre-Post Conditional
on:
  workflow_dispatch:

jobs:
  composite-node:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main

  composite-node-failure:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-failure@main