name: Nested Node Action
on:
  workflow_dispatch:

jobs:
  on-success:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main

  on-success-check:
    runs-on: self-hosted
    needs: on-success
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const run_id = ${{ github.run_id }};
            async function getSuccessJobIdFromRunId(run_id) {
                return await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs', {
                    owner: 'fhammerl',
                    repo: 'canary',
                    run_id
                })
            }

            async function getJobLogs(job_id) {
                return await github.rest.actions.downloadJobLogsForWorkflowRun({
                    owner: 'fhammerl',
                    repo: 'canary',
                    job_id
                })
            }

            getSuccessJobIdFromRunId(run_id).then(response => {
                const job_id = response.data.jobs.filter(job => job.name == "on-success")[0].id;
                getJobLogs(job_id).then(logs => {
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("PRE-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Pre-step did not run!'
                    }
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("MAIN-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Main step did not run!'
                    }
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("POST-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Post-step did not run!'
                    }

                    console.log("All checks successful!")
                });
            });

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()

      
  on-failure-job-failing:
    continue-on-error: true
    runs-on: self-hosted
    steps:
      - run: exit 1
      - uses: fhammerl/canary/nested-node-pre-post-on-failure@main
        if: failure()
      - run: echo "${{job.status}}"
        if: always()

  on-failure-job-failing-check:
    runs-on: self-hosted
    needs: on-failure-job-failing
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const run_id = ${{ github.run_id }};
            async function getSuccessJobIdFromRunId(run_id) {
                return await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs', {
                    owner: 'fhammerl',
                    repo: 'canary',
                    run_id
                })
            }

            async function getJobLogs(job_id) {
                return await github.rest.actions.downloadJobLogsForWorkflowRun({
                    owner: 'fhammerl',
                    repo: 'canary',
                    job_id
                })
            }

            getSuccessJobIdFromRunId(run_id).then(response => {
                const job_id = response.data.jobs.filter(job => job.name == "on-failure-job-failing")[0].id;
                getJobLogs(job_id).then(logs => {
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("PRE-STEP-COMPLETE") != -1).length != 0) {
                        throw 'Pre-step ran but job is failed later on step 1'
                    }
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("MAIN-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Main step did not run!'
                    }
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("POST-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Post-step did not run!'
                    }

                    console.log("All checks successful!")
                });
            });

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()


  on-composite-failure-job-success:
    continue-on-error: true
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main
        with:
          exit-code: 1
        continue-on-error: true

  on-composite-failure-job-success-check:
    runs-on: self-hosted
    needs: on-composite-failure-job-success
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const run_id = ${{ github.run_id }};
            async function getSuccessJobIdFromRunId(run_id) {
                return await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs', {
                    owner: 'fhammerl',
                    repo: 'canary',
                    run_id
                })
            }

            async function getJobLogs(job_id) {
                return await github.rest.actions.downloadJobLogsForWorkflowRun({
                    owner: 'fhammerl',
                    repo: 'canary',
                    job_id
                })
            }

            getSuccessJobIdFromRunId(run_id).then(response => {
                const job_id = response.data.jobs.filter(job => job.name == "on-composite-failure-job-success")[0].id;
                getJobLogs(job_id).then(logs => {
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("PRE-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Pre-step did not run!'
                    }
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("MAIN-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Main step did not run!'
                    }
                    if (logs.data.split(/\r?\n/).filter(line => line.indexOf("POST-STEP-COMPLETE") != -1).length == 0) {
                        throw 'Post-step did not run!'
                    }

                    console.log("All checks successful!")
                });
            });

      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: failure()

  on-composite-failure-job-failing:
    continue-on-error: true
    runs-on: self-hosted
    steps:
      - run: exit 1
      - uses: fhammerl/canary/nested-node-pre-post-on-failure@main
        with:
          exit-code: 1
        if: failure()

  on-composite-failure-job-failing-check:
      runs-on: self-hosted
      needs: on-composite-failure-job-failing
      steps:
        - uses: actions/github-script@v5
          with:
            script: |
              const run_id = ${{ github.run_id }};
              async function getSuccessJobIdFromRunId(run_id) {
                  return await github.request('GET /repos/{owner}/{repo}/actions/runs/{run_id}/jobs', {
                      owner: 'fhammerl',
                      repo: 'canary',
                      run_id
                  })
              }

              async function getJobLogs(job_id) {
                  return await github.rest.actions.downloadJobLogsForWorkflowRun({
                      owner: 'fhammerl',
                      repo: 'canary',
                      job_id
                  })
              }

              getSuccessJobIdFromRunId(run_id).then(response => {
                  const job_id = response.data.jobs.filter(job => job.name == "on-composite-failure-job-failing")[0].id;
                  getJobLogs(job_id).then(logs => {
                      if (logs.data.split(/\r?\n/).filter(line => line.indexOf("PRE-STEP-COMPLETE") != -1).length != 0) {
                          throw 'Pre-step ran but job is failed later on step 1'
                      }
                      if (logs.data.split(/\r?\n/).filter(line => line.indexOf("MAIN-STEP-COMPLETE") != -1).length == 0) {
                          throw 'Main step did not run!'
                      }
                      if (logs.data.split(/\r?\n/).filter(line => line.indexOf("POST-STEP-COMPLETE") != -1).length == 0) {
                          throw 'Post-step did not run!'
                      }

                      console.log("All checks successful!")
                  });
              });

        - run: echo 'in case of actual failure do slack webhook' && exit 1
          id: todo-slack-webhook
          if: failure()
