name: Composite Action Executes Steps Accord

on:
  workflow_dispatch:
jobs:
  action-success:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./conditional-composite
        id: composite-action
      - run: if [ -z "${{ steps.composite-action.outputs.default }}" ]; then exit 1; fi
        name: step-default
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then exit 1; fi
        name: step-success
      - run: if [[ ! -z "${{ steps.composite-action.outputs.failure }}" ]]; then exit 1; fi
        name: step-failure
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then exit 1; fi
        name: step-always

      - run: exit 1
        id: todo-slack-webhook
        if: failure()

  action-failure:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./conditional-composite
        id: composite-action
        with:
          exit-code: 1
        continue-on-error: true
      - run: if [[ ! -z "${{ steps.composite-action.outputs.default }}" ]]; then exit 1; fi
        name: step-default
      - run: if [[ ! -z "${{ steps.composite-action.outputs.success }}" ]]; then exit 1; fi
        name: step-success
      - run: if [ -z "${{ steps.composite-action.outputs.failure }}" ]; then exit 1; fi
        name: step-failure
      - run: if [ -z "${{ steps.composite-action.outputs.always }}" ]; then exit 1; fi
        name: step-always

      - run: exit 1
        id: todo-slack-webhook
        if: failure()