
name: Pre-Post Conditional

on:
  workflow_dispatch:

jobs:
  top-level-node:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/node-pre-post-on-success@main
  
  composite-node:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/nested-node-pre-post-on-success@main