name: runner-action-status
on:
  workflow_dispatch:
jobs:
  action-status-set-correctly-action-success:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - uses: ./runner/action-status
        id: action-status

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - run: exit 1
        name: Action status before should be 'Success'
        if: ${{ steps.action-status.outputs.status-before != 'Success' }}

      - run: exit 1
        name: Action status after should be 'Success'
        if: ${{ steps.action-status.outputs.status-after != 'Success' }}

  action-status-set-correctly-action-failure:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - uses: ./runner/action-status
        id: action-status
        with:
          exit-code: 1
        continue-on-error: true

      - run: exit 1
        name: Action status is not be available from job level
        if: github.action_status

      - run: exit 1
        name: Action status before should be 'Failure'
        if: ${{ steps.action-status.outputs.status-before != 'Success' }}

      - run: exit 1
        name: Action status after should be 'Failure'
        if: ${{ steps.action-status.outputs.status-after != 'Failure' }}

  nested-conditional-statuses-independent-from-each-other:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        exit-code: [0, 1]
        child-exit-code: [0, 1]
    steps:
      - uses: actions/checkout@v2
      - uses: ./runner/nested-action-status
        id: nested-action-status
        continue-on-error: true
        with:
          exit-code: ${{matrix.exit-code}}
          child-exit-code: ${{matrix.child-exit-code}}

      - run: exit 1
        name: status-error
        if: ${{ steps.nested-action-status.outputs.status-error }}

  
  action-status-not-set-on-job-level:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: exit 1
        name: Action status is not be available from job level
        if: ${{ github.action_status }}

      - uses: ./runner/action-status
        id: action-status

      - run: exit 1
        name: Action status is not be available from job level
        if: ${{ github.action_status }}

  nested-conditional-conditional-results-independent-from-each-other:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        exit-code: [0, 1]
        child-exit-code: [0, 1]
    steps:
      - uses: actions/checkout@v2
      - uses: ./runner/nested-composite-conditional-steps
        id: composite-action
        continue-on-error: true
        with:
          exit-code: ${{matrix.exit-code}}
          child-exit-code: ${{matrix.child-exit-code}}
      - run: if [ -z "${{ steps.composite-action.outputs.failure }}" ]; then exit 1; else echo "Expected a failure and got one!"; fi
        if: matrix.exit-code == 1 || matrix.child-exit-code == 1
      - run: if [ -z "${{ steps.composite-action.outputs.success }}" ]; then exit 1; else echo "Expected a success and got one!"; fi
        if: matrix.exit-code == 0 && matrix.child-exit-code == 0

  failing-composite-with-continue-on-error-does-not-fail-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: ./runner/composite-conditional-steps
        id: composite-action
        with: 
          exit-code: 1
        continue-on-error: true

