name: runner-conditional-steps

on:
  workflow_dispatch:
jobs:
  job-failing-composite-success-runs-default-success-always:
    outputs:
      default: ${{ steps.composite-action.outputs.default }}
      success: ${{ steps.composite-action.outputs.success }}
      failure: ${{ steps.composite-action.outputs.failure }}
      always: ${{ steps.composite-action.outputs.always }}
    continue-on-error: true
    name: Runs steps with no condition, success or always
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - uses: ./composite-conditional-steps
        id: composite-action
        if: always()

  job-failing-composite-success-runs-default-success-always-check:
    needs: job-failing-composite-success-runs-default-success-always
    name: Check only default(), success and always() ran
    runs-on: self-hosted
    steps:
      - run: exit 1
        id: todo-slack-webhook
        if: ${{ !(needs.job-failing-composite-success-runs-default-success-always.outputs.default && needs.job-failing-composite-success-runs-default-success-always.outputs.success && !needs.job-failing-composite-success-runs-default-success-always.outputs.failure && needs.job-failing-composite-success-runs-default-success-always.outputs.always) }}
  
  job-failing-composite-failing-runs-default-success-always:
    outputs:
      default: ${{ steps.composite-action.outputs.default }}
      success: ${{ steps.composite-action.outputs.success }}
      failure: ${{ steps.composite-action.outputs.failure }}
      always: ${{ steps.composite-action.outputs.always }}
    continue-on-error: true
    name: Runs steps with no condition, success or always
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: exit 1
      - uses: ./composite-conditional-steps
        with:
          exit-code: 1
        id: composite-action
        if: always()

  job-failing-composite-failing-runs-default-success-always-check:
    needs: job-failing-composite-failing-runs-default-success-always
    name: Check only failure() and always() ran
    runs-on: self-hosted
    steps:
      - run: echo 'in case of actual failure do slack webhook' && exit 1
        id: todo-slack-webhook
        if: ${{ !(!needs.job-failing-composite-failing-runs-default-success-always.outputs.default && !needs.job-failing-composite-failing-runs-default-success-always.outputs.success && needs.job-failing-composite-failing-runs-default-success-always.outputs.failure && needs.job-failing-composite-failing-runs-default-success-always.outputs.always) }}
