name: Node Action (top-level)

on:
  workflow_dispatch:
jobs:
  action-success:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/node-pre-post-on-success@main
        id: action-success
    outputs:
      pre-result: ${{ steps.action-success.outputs.pre-result }}
      post-result: ${{ steps.action-success.outputs.post-result }}

  action-success-check:
    runs-on: self-hosted
    needs: action-success
    steps:
      - run: echo ${{ needs.action-success.outputs.pre-result }} 
      - run: echo ${{ needs.action-success.outputs.post-result }} 
