name: Node Action (top-level)

on:
  workflow_dispatch:
  push:
jobs:
  action-success:
    runs-on: self-hosted
    steps:
      - uses: fhammerl/canary/node-pre-post-on-success@main
        id: action-success

  action-success-check:
    runs-on: self-hosted
    needs: action-success
    steps:
      - run: echo ${{ toJSON(needs.action-success) }}
